# Cloud Build configuration for reGen Server
# This file defines the build and deployment pipeline for Google Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/regen-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/regen-server:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'
    
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/regen-server:$COMMIT_SHA'
    id: 'push-image-sha'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/regen-server:latest'
    id: 'push-image-latest'
    
  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'regen-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/regen-server:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'APP_ENV=prod'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--port'
      - '8080'
    id: 'deploy-cloud-run'

# Substitutions for customizable deployment parameters
substitutions:
  _REGION: 'us-central1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '1Gi'
  _CPU: '1'
  _TIMEOUT: '3600s'  # Increased for WebSocket voice conversations
  _CONCURRENCY: '80'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/regen-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/regen-server:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for the entire build (30 minutes)
timeout: '1800s'
