"""Add user and profile history tables

Revision ID: 001
Revises: 
Create Date: 2026-01-10 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rg_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guest_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rg_users'))
    )
    op.create_index(op.f('ix_guest_id'), 'rg_users', ['guest_id'], unique=True)
    op.create_index(op.f('ix_email'), 'rg_users', ['email'], unique=False)
    
    op.create_table('rg_profile_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['rg_users.id'], name=op.f('fk_rg_profile_history_user_id_rg_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rg_profile_history'))
    )
    op.create_index(op.f('ix_user_id'), 'rg_profile_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='rg_profile_history')
    op.drop_table('rg_profile_history')
    op.drop_index(op.f('ix_email'), table_name='rg_users')
    op.drop_index(op.f('ix_guest_id'), table_name='rg_users')
    op.drop_table('rg_users')
    # ### end Alembic commands ###