"""Add profile privacy table

Revision ID: 005
Revises: 004
Create Date: 2026-01-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rg_profile_privacy',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('hidden_sections', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['rg_users.id'], name=op.f('fk_rg_profile_privacy_user_id_rg_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_rg_profile_privacy'))
    )
    op.create_index(op.f('ix_rg_profile_privacy_user_id'), 'rg_profile_privacy', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rg_profile_privacy_user_id'), table_name='rg_profile_privacy')
    op.drop_table('rg_profile_privacy')
    # ### end Alembic commands ###
